### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.6.0:process

### ISSUE THREAD

**Issue by jaehwanspin** [avob/OpenADR#1]
> $ git clone --recursive https://github.com/avob/OpenADR.git
> $ cd ./OpenADR
> $ sudo mvn clean package install -Dmaven.test.skip=true -e
[INFO] OpenADR ............................................ SUCCESS [  2.214 s]
[INFO] OpenADRSecurity .................................... SUCCESS [  5.582 s]
[INFO] OpenADRHTTPClient .................................. SUCCESS [  1.419 s]
[INFO] OpenADRModel20a .................................... SUCCESS [ 14.116 s]
[INFO] OpenADRHTTPClient20a ............................... SUCCESS [  3.301 s]
[INFO] OpenADRModel20b .................................... FAILURE [ 11.307 s]
[INFO] OpenADRHTTPClient20b ............................... SKIPPED
[INFO] OpenADRServerVTNCommon ............................. SKIPPED
[INFO] OpenADRServerVEN20a ................................ SKIPPED
[INFO] OpenADRServerVTN20a ................................ SKIPPED
[INFO] OpenADRServerVEN20b ................................ SKIPPED
[INFO] OpenADRServerVTN20b ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.821 s
[INFO] Finished at: 2019-03-25T09:06:00Z
[INFO] Final Memory: 68M/704M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.6.0:process (default) on project OpenADRModel20b: Resources archive cannot be found.: Could not find artifact com.avob.openadr.model:OpenADRModel20b:jar:0.0.1-SNAPSHOT
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=com.avob.openadr.model -DartifactId=OpenADRModel20b -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=com.avob.openadr.model -DartifactId=OpenADRModel20b -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   com.avob.openadr.model:OpenADRModel20b:jar:0.0.1-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]

-- env --
Windows 10 WSL Ubuntu 18.04
openjdk-8-jdk
Apache Maven 3.5.2

**Comment by bzanni-avob** [comment]
Hi,
This should have been fixed by last commits.
Thanks a lot for repporting the issue !

**Comment by jaehwanspin** [comment]
thanks for your instruction but how can i run this app???

**Comment by zanni** [comment]
Hi,

I updated a bit the readme. You should be able to run a VM with VTN20b + Control UI App + Node-red containing a simulator of a VEN.
VTN20b endpoint:
https://vtn.oadr.com:8181/testvtn
VTN20b swagger:
https://vtn.oadr.com:8181/testvtn/swagger-ui.html
UI Control:
https://vtn.oadr.com:8080/oadr-vtn20b-ui/
Node-red terminal
http://localhost:1880/#

You need to configure the DNS of your host by adding "127.0.0.1 vtn.oadr.com"

Don't forget that everything here is work in progress ! 

Hope it can help

**Comment by zanni** [comment]
Forgot mention that you need to import admin x509 certificates in you browser in order to access previously mentioned HTTPS address.
You can found those certificates in cert/cert/admin.oadr.com(.crt/.key)
This certificate has been signed by self-signed certificate authority.
You can found CA certificate in cert/cert/oadr.com(.crt/.key)
