### ISSUE TITLE
install dependancies

### ISSUE THREAD

**Issue by bbartling** [avob/OpenADR#15]
Hello,

Any chance for a tip installing dependencies? I also put in a ticket on stackoverflow:
https://unix.stackexchange.com/questions/617625/install-required-packages-help-from-a-github-repo

Not sure if makes a difference at all I have a whole computer running Ubuntu 16.04 LTS versus a VM.

Thank you!
Ben

**Comment by zanni** [comment]
Hi,

I'm not sure you can install oraclejdk from ubuntu repo any more because an account on oracle.com is now mandatory. The project is compatible with openjdk: https://doc.ubuntu-fr.org/openjdk
I updated the project to java 11 so if you want to test/compile the project you must install a java 11 jdk.
If you just want to run a VEN/VTN, you can use docker. The command "docker-compose up" creates a configured VEN / VTN full stack within several docker containers.
I updated the README to reflect those modifications.

Bertrand

**Comment by bbartling** [comment]
Bertrand,

Ill try the Docker route for the time being. Thank you so much!

Just one other question I have at the moment about the repo:

- The front end VEN (node red) and back end VTN (Java) exist on the same machine just for testing purposes, right? Would these be separate at some future date in time in production mode where the node red VEN would be remote in a building and the VTN would reside on the utility provider LAN/server platform.. OR would the front end node.js & backend java always need to exist together?

- Would I ever be able to test Java VTN backend this with other open ADR VEN devices? Would it matter if I am using Docker for this?


Thanks!
Ben

**Comment by zanni** [comment]
Hi Ben,

- Yes for testing/development purpose you can run every module of the OADR stack on your computer using docker container. In a production environment, VENs and VTNs are generally separated, VENs are more on the building side and the VTNs more on utility side. It is very unlikely that VEN and VTN will be on the same hardware, even if it can happens (the aggregator case for example).

- Yes you can use any other VEN / VTN 2.0b with the java VEN / VTN 2.0b. Oadr 2.0a should be compatible too but I have never tested this settings. It does not matter for the VEN or VTN if it is run on container, a VM or directly on the host.

- No using docker, you only have to install Docker client. Docker stack are supposed to be compatible with every OS . You might create your own stack, for example by removing the VEN to work on your own VEN implementation (look at docker-compose.yml).

Bertrand

**Comment by bbartling** [comment]
Hi Bertrand, sorry the wheels have been moving very slow for being able to test this... Been too busy

For the Java backend, can that run on Heroku or AWS for testing purposes? Would there be any chance can you tell me what Java web stack it runs? Sorry not familiar with Java. Thank you!

**Comment by zanni** [comment]
Hi Ben,

Heroku supports docker-compose so you should be able to replicate on Heroku what you can do in local using docker-compose, but I have never tested it
https://devcenter.heroku.com/articles/local-development-with-docker-compose

You also can use build docker image in AWS using service like EKS
https://aws.amazon.com/fr/eks/?whats-new-cards.sort-by=item.additionalFields.postDateTime&whats-new-cards.sort-order=desc&eks-blogs.sort-by=item.additionalFields.createdDate&eks-blogs.sort-order=desc

Internally, this implementation uses spring-boot as MVC framework.

Bertrand

**Comment by bbartling** [comment]
Hi Bertrand,

I am finally getting around back to testing this again :)

Can I run the docker container on Windows OS to test the dummy VTN & VEN? I notice the Ubuntu 16.04 requirement is gone..

Thank you!
Ben

**Comment by zanni** [comment]
Hi Ben,

Yes you can use the project as long as docker is installed on your environment but I have never tested it on Windows.

Bertrand

**Comment by bbartling** [comment]
Ok I may give the docker desktop for Windows a go

**Comment by bbartling** [comment]
Bertrand,

Could you give me a tip? Sorry for being such a newb with this stuff... I know you also said not tested on Windows docker as well.

So on my Windows 10 desktop I have docker desktop installed with Ubuntu 20.04 LTS image.

I git cloned the repo to my desktop and then from the command prompt in the cloned repo directory ran `docker-compose up --build` . Also not sure if this is Ok, but in Windows just running the shell script `generate_test_cert.sh` seemed to execute.

During the docker build process it errors after the Postgres image on the open fire process:

![image](https://user-images.githubusercontent.com/29737117/105870321-c431fc80-5fbd-11eb-8d3e-56b31a0734fd.png)


I also realized I am above the recommended docker version too for the project:
![image](https://user-images.githubusercontent.com/29737117/105867021-39033780-5fba-11eb-8446-99fd1516390e.png)


Could you ever recommend something for me to try? Like install a Ubuntu VM (version?) and repeat entire process with correct docker version, etc... Any tips on the process above also Gratefully appreciated as I don't have a ton of docker experience.

Thank you so much!
Ben

**Comment by zanni** [comment]
Hi Ben,

Your certificates seems to not have been generated by command ./generate_test_cert.sh

This script shall have created a folder «  cert » at the root path of your project. This folder should have been populated with several «  *.oadr.com <http://oadr.com/>.* » certification files, including the one which is missing in the error you sent: oar.com.crt

generate_test_cert.sh rely on «  openssl » command, maybe it is not installed on your environment. 

Could you send me the error / message return by the script generate_test_cert.sh ?

Bertrand

**Comment by zanni** [comment]
Yes there are some problems:

	- the script uses «  keytool » binary to generate java certificate store, which seems not to be accessible on your host
	./generate_test_cert.sh: line 92: keytool: command not found

    - the generation of self signed authority (gen_selfsigned_key_crt) fail in your case because the subject is C:/Program Files/Git/C=FR/ST=Paris/L=Paris/O=Avob/OU=Avob/CN=oadr.com <http://oadr.com/> while it is supposed to be /C=FR/ST=Paris/L=Paris/O=Avob/OU=Avob/CN=oadr.com <http://oadr.com/>. I really don’t know why the «  c:/Program Files … » is added.

Now I know this script is not compatible with Windows I might write some code to generate the certificates in docker. However I can't promise you I will do it and more important that I will do it in a short time span.

However, I can send you by mail an archive containing those certificates if you want.

**Comment by bbartling** [comment]
Ok great. Just email address then? bbartling@slipstreaminc.org is my work email

**Comment by bbartling** [comment]
Thanks again

**Comment by bbartling** [comment]
Well it looks like there is a little bit more going on with the certs, thanks for the email btw.

Here's [git gist ](https://gist.github.com/bbartling/ca4c2db0173887b116d2aa0fc192415b)of the cmd prompt.

This is still on the windows docker version I have yet to complete the Linux VM.

Would my next steps be opening another command prompt in the `OpenADR` directory and running the commands as instructed:

```
mvn clean verify

mvn clean package -P external,frontend 

mvn clean package
```

Would I need to incorporate docker into those commands or just run them as instructed? I also thought I saw something about a self sign on web browser is that for configurations?

Thank you!

**Comment by zanni** [comment]
Look like there is problem with line endings (windows vs unix)
https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory <https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory>
dummy-drprogram_1  | standard_init_linux.go:219: exec user process caused: no such file or directory
Also java seems to dislike initial heap settings:
go to .docker/vtn20b/oadr-vtn20b.conf and change JAVA_OPTS="-Xmx256M » to JAVA_OPTS="-Xmx256m » 
Invalid maximum heap size: -Xmx256M

**Comment by bbartling** [comment]
Ok, so go #2 on the linux ubuntu VM, here's a [gist ](https://gist.github.com/bbartling/ca4c2db0173887b116d2aa0fc192415b#file-gistfile1-txt)of the cmd prompt after running the docker process to --build.

Would I still need to do any of the these steps next? If so how would I implement these commands? (thru another cmd prompt or docker?)
```
mvn clean verify

mvn clean package -P external,frontend 

mvn clean package
```

I'm learning about open ADR especially about the types of open ADR types of scenario's a utility provider could implement. I think this is where the rabbit MQ comes into play. Also is the dummy VEN device still node-red?

Curious about next steps on how to poke around in here even more :) Like simulate utility provider program --> send signal from VTN --> VEN

Thanks so much on the help, my background is more on the building efficiency / building automation side not programming :)

**Comment by bbartling** [comment]
Is there a web browser interface at all for the VTN? OR on the node red VEN side?
