### ISSUE TITLE
"/usr/share/openfire/resources/security already exists as a link"

### ISSUE THREAD

**Issue by AbdullahAtilla** [avob/OpenADR#2]
> fatal: [vtn20b]: FAILED! => {"changed": false, "gid": 123, "group": "openfire", "mode": "0777", "msg": "/usr/share/openfire/resources/security already exists as a link", "owner": "openfire", "path": "/usr/share/openfire/resources/security", "size": 22, "state": "link", "uid": 116}

The error occurs when I use the command "**vagrant up**"
I've check the requirements and ensure all the tools have installed with the specified versions.

**Comment by bzanni-avob** [comment]
Hi,
Error seems to be related to the provisioning of Openfire, a XMPP backend I'm working on to integrate XMPP transport. You can skip this feature by removing "../../roles/oadr-openfire" line in file vtn20b_postgres/provisioning/playbook.yml

However I would like to help resolve this problem but I cannot reproduce the error on my environment, can you check that your git repo is up to date on master branch. Error might be related to Vagrant and Vagrant ansible plugin, can you check your version of these sofware ? Mine are:
Vagrant: 2.1.4 (vagrant -v)
Vagrant ansible: 0.2.2 (vagrant plugin list)

Can you give me the exact ansible task where the error occurs (ex: TASK [../../roles/oadr-openfire : check if openfire already installed] ********) ? 
Error is obviously related to role openfire but it can be interesting to know where exactly it happened in the role.

**Comment by AbdullahAtilla** [comment]
Hey, 
Removing "../../roles/oadr-openfire" line has solved the problem. Thanks.

I'm using;
_Vagrant 2.0.3
vagrant-ansible (0.0.5)_

The exact ansible task where the error occur is;
_TASK [../../roles/oadr-openfire : Setup security ownership]_

I think it is related with the part;
    _name: Setup security ownership
    file:
      path: /usr/share/openfire/resources/security
      state: directory
      recurse: yes
      owner: openfire
      group: openfire_

in _OpenADR/devops/roles/oadr-openfire/tasks/main.yml_ file.

Thank you for your respond.
