### ISSUE TITLE
Cannot build up nodered

### ISSUE THREAD

**Issue by steven-smpct** [avob/OpenADR#3]
When I try to bring up the the vm I get:
TASK [../../roles/nodered-oadr-ven : Install node-gyp build dependencies] ******
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{item}}"`, please use `name: ['build-essential']` and 
remove the loop. This feature will be removed in version 2.11. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [nodered] (item=[u'build-essential']) => {"ansible_loop_var": "item", "changed": false, "item": ["build-essential"], "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}

PLAY RECAP *********************************************************************
nodered                    : ok=12   changed=11   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

I am running ubuntu 18.04 and I followed the instructions on the README.

**Comment by zanni** [comment]
It was due to a backward incompatibility with ansible 'apt' function.

This issue should have been solved with my last commit

**Comment by steven-smpct** [comment]
Was able to build and bring up the VM. But after that, not all the URL that are provided work. They give me a connection refused.

**Comment by ReddyAravindAru** [comment]
same here @steven-smpct 

I can only access below end points:

VTN RabbitMQ Management UI: http://192.168.33.2:15672
VTN Openfire Management UI: http://192.168.33.2:9090

Below end points cannot be accessed. I uncommented port 8181 line in vagrant file.

https://vtn.oadr.com:8181/testvtn/index.html - HTTP ERROR 403
https://vtn.oadr.com:8181/testvtn - HTTP ERROR 403
https://vtn.oadr.com:8181/testvtn/swagger-ui.html - This page isn’t working (HTTP ERROR 401)

http://192.168.33.2:1880/ - 192.168.33.2 refused to connect.
http://192.168.33.2:1880/ui/#!/0 - 192.168.33.2 refused to connect.

**Comment by zanni** [comment]
fix ansible recipe
