### ISSUE TITLE
Control UI not accessable

### ISSUE THREAD

**Issue by akshay9502** [avob/OpenADR#5]
I have 2 issues in here
1. On successfully running the `OpenADR/devops/vtn20b_postgres` vagrant file, the control UI is not up and not accessible, In the Vagrant file port `8181` where the control UI is, is commented. I have tried uncommenting it as well but did not work.

2. When I try to run node-red one, I have the following error
<img width="545" alt="Screenshot 2020-05-05 at 3 21 37 PM" src="https://user-images.githubusercontent.com/50326209/81054278-1e48da00-8ee4-11ea-8aa5-12c8a9c714c3.png">

**Comment by zanni** [comment]
Hi,

For the first issue, you should try to access control UI using "/testvtn/index.html" and not "/testvtn/". 
This is actually a problem with Jetty I need to investigate.

For the second issue, you should do a 'git clone https://github.com/avob/node-red-contrib-oadr-ven' in devops/nodered folder.

I know I need to work on those issues but I do not have much time currently. Any merge request would be greatly appreciated

bertrand

**Comment by ReddyAravindAru** [comment]
Hello zanni,

I can only access below end points:

VTN RabbitMQ Management UI: http://192.168.33.2:15672
VTN Openfire Management UI: http://192.168.33.2:9090


Below end points cannot be accessed. I uncommented port 8181 line in vagrant file.

https://vtn.oadr.com:8181/testvtn/index.html  - **HTTP ERROR 403**
https://vtn.oadr.com:8181/testvtn - **HTTP ERROR 403**
https://vtn.oadr.com:8181/testvtn/swagger-ui.html - **This page isn’t working (HTTP ERROR 401)**

http://192.168.33.2:1880/ - **192.168.33.2 refused to connect.**
http://192.168.33.2:1880/ui/#!/0 - **192.168.33.2 refused to connect.**

Please help. Thanks in advance.

**Comment by ReddyAravindAru** [comment]
@akshay9502  Are you able to access all the links and everything is fine for you? I need some help please.

**Comment by zanni** [comment]
up spring dependencies

**Comment by parashar18** [comment]
> @akshay9502 Are you able to access all the links and everything is fine for you? I need some help please.

Hello, Did you able to solve the issue?
