### ISSUE TITLE
VTNTest not accesible

### ISSUE THREAD

**Issue by arihantdaga** [avob/OpenADR#6]
Hi. This project is a great work. I wanted to test it but i am getting an error.
I am seeing this when trying to open testvtn page. Am i missing something here? 

![Selection_034](https://user-images.githubusercontent.com/4976460/81176441-c92fc580-8fc2-11ea-95bb-caa5458e3b91.png)

Also is there anyway to check logs of the application ?

**Comment by arihantdaga** [comment]
Got it working. Had to use /index.html 
Its working now. Thank you.

**Comment by zanni** [comment]
Hi,

Thanks you for using my project !

Yes I was working on your issue, I needlessly upgrading spring-boot before figuring out like you that /index.html was missing.

However it is not supposed to work like that and you should be able to access home page with «  / ». I guess jetty behavior as changed. 

I would like to find out what happened but I do not have much time currently. Any merge request would be greatly appreciated !

Bertrand
