### ISSUE TITLE
Unable to SSH to vagrant box

### ISSUE THREAD

**Issue by devendraap** [avob/OpenADR#9]
I am stuck during deployment of VM during SSH phase.
My current setup:
- virtualbox/bionic-updates,now 5.2.34 
- Vagrant 2.0.2 on EC2 remote server.
- ansible 2.9.9
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

This might be causing SSH issue.

![image](https://user-images.githubusercontent.com/17588085/83561498-929f8900-a535-11ea-9317-b97491466ad5.png)

The vagrant and Virtualbox version are not documented.
Could you add them please?

**Comment by devendraap** [comment]
I also tried the nodered and vtn20b_postgres deployments and both show similar behaviour

**Comment by devendraap** [comment]
When I run deploy vagrant in debug mode, I am getting
`videocap="off"
videocap_audio="off"
videocapscreens=0
videocapfile="/home/ubuntu/VirtualBox VMs/ubuntu-16.04-amd64_1591128181465_92351"
videocapres=1024x768
videocaprate=512
videocapfps=25
videocapopts=`

Does this VM require GUI support?

**Comment by yashpatel20** [comment]
I am also facing the same issue. The vagrant and Virtualbox version are not documented.
Could you add them please?
